// <auto-generated />
using APIAmbiental.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace APIAmbiental.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240626012742_AddCondicoesAmbientais")]
    partial class AddCondicoesAmbientais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIAmbiental.Models.CondicoesAmbientais", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("contatoEmergencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("desastreNatural")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("qualidadeAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("temperatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("umidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id");

                    b.ToTable("CondicoesAmbientais", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
